---

- name: deploy EC2
  hosts: localhost
  gather_facts: False
  roles:
    - deploy
  tags:
    - deploy

- name: bootstrap
  hosts: tag_Name_BYOCM_dev_instance
  become: true
  vars:
    ansible_ssh_private_key_file: ~/.ssh/BYOCM-dev-key
  roles:
    - bootstrap
  tags:
    - bootstrap

- name: conifigure database
  hosts: tag_Name_BYOCM_dev_database
  roles:
    - database
  tags:
    - database

- name: deploy SSL
  hosts: tag_Name_BYOCM_dev_instance
  become: true
  roles:
    - letsencrypt
  tags:
    - letsencrypt

- name: configure docker
  hosts: tag_Name_BYOCM_dev_instance
  become: true
  roles:
    - docker
  tags:
    - docker
