---

# AWS
aws_region: eu-west-2

# VPC
vpc_name: "{{ project_name }}-VPC"
vpc_cidr: 172.31.0.0/23
vpc_tenancy: default

# Subnet
subnets:
  BYOCM-subnet-A:
    AZ: "{{ aws_region}}a"
    subnet_cidr: 172.31.0.0/24
  BYOCM-subnet-B:
    AZ: "{{ aws_region }}b"
    subnet_cidr: 172.31.1.0/24

# IGW
igw_name: "{{ project_name }}-IGW"

# Routingtable
routingtable_name: "{{ project_name }}-RT"

# For flexibility I've used a dict to describe what my instances should look like in AWS
instances:
  BYOCM:
    count: 1
    instance_type: t2.micro
    public_ip: True
    subnet_id: "{{ subnet_id | first }}"
    security_groups:
      rules:
        - { proto: tcp, from_port: 80, to_port: 80, cidr_ip: 0.0.0.0/0 }
        - { proto: tcp, from_port: 443, to_port: 443, cidr_ip: 0.0.0.0/0 }
        - { proto: tcp, from_port: 22, to_port: 22, cidr_ip: 35.177.169.103/32 }
        - { proto: tcp, from_port: 22, to_port: 22, cidr_ip: 172.31.0.150/32 }

rds_instances:
  BYOCM:
    engine: mariadb
    version: 10.2.11
    size: 10
    instance_type: db.t2.micro
    username: root
    password: SqZpKKsxde

# placeholder
project_name: BYOCM
env: dev
